version: '3.8'

services:
  web:
    build: ./web
    ports:
      - "8080:80"
    volumes:
      - ./web/public:/var/www/html
      - ./web/includes:/var/www/includes
    environment:
      - MONITOR_PASSWORD=monitor123
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: vuln-bugtracker-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bugtracker
      MYSQL_USER: bugtracker_user
      MYSQL_PASSWORD: bugtracker_password
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u$$MYSQL_USER", "-p$$MYSQL_PASSWORD"]
      interval: 5s
      timeout: 5s
      retries: 5

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: vuln-bugtracker-phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: bugtracker_user
      PMA_PASSWORD: bugtracker_password
